spring:
  #http:
    #multipart:
      #maxRequestSize: 800Mb
  servlet:
    multipart:
      maxFileSize: 800MB
      maxRequestSize: 800MB
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql
  reasonable: false
feign:
  hystrix:
    enabled: false
  httpclient:
    enabled: true
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
ribbon:
  ConnectTimeout: 6000
  ReadTimeout: 6000
  OkToRetryOnAllOperations: true
  MaxAutoRetriesNextServer: 2
  MaxAutoRetries: 1
mybatis:
  mapper-locations: classpath:com/zyn/storage/file/dao/mapping/*.xml
  type-aliases-package: com.zyn.storage.file.entity
management:
  endpoints:
    web:
      #Actuator 默认所有的监控点路径都在/actuator/*，当然如果有需要这个路径也支持定制。
      base-path: /monitor
      #Actuator 默认只开放了两个端点 /actuator/health 和 /actuator/info
      exposure:
        #打开所有的监控点
        include: '*'
        #屏蔽env,beans监控点
        exclude: env,beans
  endpoint:
    health:
      #详细显示health信息
      show-details: always
      #启用接口关闭 Spring Boot (post请求)
      shutdown:
        enabled: true
  health:
    defaults:
      enabled: true
